### ISSUE TITLE
Could not open comm

### ISSUE THREAD

**Issue by peller** [ipython/ipywidgets#103]
I installed Jupyter Notebook according to the [latest README](https://github.com/jupyter/notebook/blob/2b5ba10ce980912de1c456c665aee7af2a2e6211/README.md) then followed by installing ipywidgets  

When opening the [Widget Basics example](https://github.com/ipython/ipywidgets/blob/master/examples/Widget%20Basics.ipynb) notebook, the import cell worked fine, but the cells creating widgets failed.  These errors were shown in the browser console from executing `IntSlider()`:

```
Error: Could not open comm
    at new Error (native)
    at Error.WrappedError (http://192.168.100.100:8888/static/notebook/js/main.min.js?v=5481c6cbbfa3491e70ffb5a7c79f89f7:12706:25)
    at reject (http://192.168.100.100:8888/static/notebook/js/main.min.js?v=5481c6cbbfa3491e70ffb5a7c79f89f7:12785:33)
Error: Couldn't process kernel message
    at new Error (native)
    at Error.WrappedError (http://192.168.100.100:8888/static/notebook/js/main.min.js?v=5481c6cbbfa3491e70ffb5a7c79f89f7:12706:25)
    at reject (http://192.168.100.100:8888/static/notebook/js/main.min.js?v=5481c6cbbfa3491e70ffb5a7c79f89f7:12785:33)
Error: Couldn't process kernel message
    at new Error (native)
    at Error.WrappedError (http://192.168.100.100:8888/static/notebook/js/main.min.js?v=5481c6cbbfa3491e70ffb5a7c79f89f7:12706:25)
    at reject (http://192.168.100.100:8888/static/notebook/js/main.min.js?v=5481c6cbbfa3491e70ffb5a7c79f89f7:12785:33)
Error: Couldn't process kernel message
    at new Error (native)
    at Error.WrappedError (http://192.168.100.100:8888/static/notebook/js/main.min.js?v=5481c6cbbfa3491e70ffb5a7c79f89f7:12706:25)
    at reject (http://192.168.100.100:8888/static/notebook/js/main.min.js?v=5481c6cbbfa3491e70ffb5a7c79f89f7:12785:33)
Error: Couldn't process kernel message
    at new Error (native)
    at Error.WrappedError (http://192.168.100.100:8888/static/notebook/js/main.min.js?v=5481c6cbbfa3491e70ffb5a7c79f89f7:12706:25)
    at reject (http://192.168.100.100:8888/static/notebook/js/main.min.js?v=5481c6cbbfa3491e70ffb5a7c79f89f7:12785:33)
Error: Couldn't process kernel message
    at new Error (native)
    at Error.WrappedError (http://192.168.100.100:8888/static/notebook/js/main.min.js?v=5481c6cbbfa3491e70ffb5a7c79f89f7:12706:25)
    at reject (http://192.168.100.100:8888/static/notebook/js/main.min.js?v=5481c6cbbfa3491e70ffb5a7c79f89f7:12785:33)
Error: Couldn't process kernel message
    at new Error (native)
    at Error.WrappedError (http://192.168.100.100:8888/static/notebook/js/main.min.js?v=5481c6cbbfa3491e70ffb5a7c79f89f7:12706:25)
    at reject (http://192.168.100.100:8888/static/notebook/js/main.min.js?v=5481c6cbbfa3491e70ffb5a7c79f89f7:12785:33)
Error: Couldn't process kernel message
    at new Error (native)
    at Error.WrappedError (http://192.168.100.100:8888/static/notebook/js/main.min.js?v=5481c6cbbfa3491e70ffb5a7c79f89f7:12706:25)
    at reject (http://192.168.100.100:8888/static/notebook/js/main.min.js?v=5481c6cbbfa3491e70ffb5a7c79f89f7:12785:33)
Error: Couldn't process kernel message
    at new Error (native)
    at Error.WrappedError (http://192.168.100.100:8888/static/notebook/js/main.min.js?v=5481c6cbbfa3491e70ffb5a7c79f89f7:12706:25)
    at reject (http://192.168.100.100:8888/static/notebook/js/main.min.js?v=5481c6cbbfa3491e70ffb5a7c79f89f7:12785:33)

```
@lbustelo

**Comment by lbustelo** [comment]
I'm still having similar issues even with following the instructions after fixes to #99 .

**Comment by wellecks** [comment]
+1 I'm seeing similar issues as well

**Comment by jasongrout** [comment]
There have been some recent changes in the notebook as it was released.  I just tried with the released version of the notebook repo, along with the master version of this repo, and I don't see this error.  I do see lots of other things with the notebooks that need to be fixed, but that's a separate issue.

Can you try one more time, with the 4.x released version of the notebook?

**Comment by jdfreder** [comment]
I think this was related to setup work that was going on, I think it should be fixed now.  I had to reinstall, in a painful way.  Remove all pyc, remove ipython widget related stuff in site packages, and fix some permissions on some of my files - and only then did the reinstall work.

**Comment by peller** [comment]
I did a pull and reran pip install on ipywidgets on top of the latest from the jupyter repository and got the same comm error.

I had to install bower manually in order to get a clean install for ipywidgets, otherwise the less imports were unable to find bootstrap dependencies.

**Comment by jdfreder** [comment]
This is probably the same problem encountered here: https://github.com/ipython/ipywidgets/issues/117  

Just copying the relevant part of my response from there for convenience, because it should also take care of bower and related:

>  pip should have done this for you though...  Was there any other errors during pip install?  A lot of times it's just a permission error that occurs because something was installed with sudo when it shouldn't have been.

**Comment by peller** [comment]
Yes, that's exactly the problem I had when installing (the exact permission error revealed itself only when running `npm install` not `pip`

However, at runtime, I still get the comm failures on console and the widgets fail to show.

**Comment by jdfreder** [comment]
Hmm, strange.  Are your other dependencies up to date?  i.e. notebook, jupyter_client, ipython, traitlets, etc..

**Comment by peller** [comment]
I'm a new user and the git clone and entire environment was fresh and run in vagrant when I reported the issue.

**Comment by jdfreder** [comment]
1. Are you able to execute code in the notebook?
2. Can you share the errors from both the Javascript console and the system console?

**Comment by jdfreder** [comment]
Also, are there any errors in the system console (backend)?

**Comment by peller** [comment]
>Are you able to execute code in the notebook?

yes

>Also, are there any errors in the system console (backend)?

nothing interesting on the back end.  But I do notice now that I have a JS error loading the page.  Looks like the root cause:

GET http://192.168.100.100:8888/nbextensions/widgets/notebook/js/extension.js req.load @ require.js?v=48113850fe201a07d2c2940a000ce103:1918context.load @ require.js?v=48113850fe201a07d2c2940a000ce103:1659Module.load @ require.js?v=48113850fe201a07d2c2940a000ce103:828Module.fetch @ require.js?v=48113850fe201a07d2c2940a000ce103:818Module.check @ require.js?v=48113850fe201a07d2c2940a000ce103:848Module.enable @ require.js?v=48113850fe201a07d2c2940a000ce103:1161context.enable @ require.js?v=48113850fe201a07d2c2940a000ce103:1531(anonymous function) @ require.js?v=48113850fe201a07d2c2940a000ce103:1146(anonymous function) @ require.js?v=48113850fe201a07d2c2940a000ce103:132each @ require.js?v=48113850fe201a07d2c2940a000ce103:57Module.enable @ require.js?v=48113850fe201a07d2c2940a000ce103:1098Module.init @ require.js?v=48113850fe201a07d2c2940a000ce103:782(anonymous function) @ require.js?v=48113850fe201a07d2c2940a000ce103:1435
main.min.js?v=7b4db783581d1ec40d6f1f6c4c47c0c0:30287 ipywidgets package not installed.  Widgets are not available.

**Comment by jdfreder** [comment]
> Yes, that's exactly the problem I had when installing (the exact permission error revealed itself only when running npm install not pip
> 
> However, at runtime, I still get the comm failures on console and the widgets fail to show.

Sorry, maybe I interpreted your post, did you ever get npm install to run without the permission error like I suggested earlier?

**Comment by peller** [comment]
TBH, I can't remember.  I think I ran sudo npm install to get around the problem.  I'll have to try again from scratch.

**Comment by jdfreder** [comment]
Try to get it working without sudo.  Once you do, I don't think you'll have problems.  Also, all of 4.0 has been released, so if you're still having problems, I suggest you try with that, that way I can be sure you have all of the right versions of things.  Working on master post big split is hard, because versions may mismatch and you may end up in a not working state.

**Comment by jdfreder** [comment]
@peller any luck with this?

**Comment by rodsenra** [comment]
I had this same problem, but I fixed it simply by changing from:
    from IPython.html.widgets import interactive, FloatSliderWidget
to:
    from ipywidgets import interactive, FloatSlider

**Comment by aldanor** [comment]
Same problem here, with the latest jupyter/notebook/ipywidgets. Notebooks work fine, but widgets don't.
